install.packages("lobstr")
install.packages("devtools")
devtools::install_github('coolbutuseless/uint8')
install.packages("pryr")
install.packages("gmp")
install.packages("float")
install.packages("Rcpp")
install.packages("Matrix")
install.packages("mvtnorm")
install.packages("microbenchmark")
install.packages("Rlinsolve", dependencies=TRUE)
install.packages("SparseM", dependencies=TRUE)
install.packages("ggplot2", dependencies=TRUE)
install.packages("statmod", dependencies=TRUE)
install.packages("scatterplot3d", dependencies=TRUE)
